### ISSUE TITLE
add resources to the readme

### ISSUE THREAD

**Issue by memoryruins** [rep-nop/barnacleboy#7]
Listing any resources that have helped while writing barnacleboy in the readme would be very much appreciated!

The three sent in our conversation on discord:

> http://bgb.bircd.org/pandocs.htm the PanDocs are IMMENSELY helpful, it covers so much stuff
http://pastraiser.com/cpu/gameboy/gameboy_opcodes.html this gives a much nicer view of the instructions and their corresponding opcodes
http://marc.rawer.de/Gameboy/Docs/GBCPUman.pdf has great stuff in it too regarding the CPU along with a couple other bits and pieces that are/aren't in the PanDocs

**Comment by avivace** [comment]
@memoryruins Check https://github.com/gbdev/awesome-gbdev !
